### ISSUE TITLE
`math.rs` not finished

### ISSUE THREAD

**Issue by Bricklou** [rust-tutorials/learn-opengl#2]
Hello,

I began the tutorial but I can't continue because the file `math.rs` is not finished and have just `unimplemented!()` calls. Is it possible to give me some information about how fill the file properly ?

**Comment by Lokathor** [comment]
Oh my.

Uhm, I think I wrote much of the math usage based on other math libs (nalgebra-glm, ultraviolet, etc) then made math.rs but didn't fill it in.

I'll try to do this soon! Until then, you can use any other math crate. The types and names should all be familiar.

**Comment by Bricklou** [comment]
Thanks !
Apart from that, the course and examples are great for learning OpenGL with Rust.

**Comment by Lokathor** [comment]
I've just updated all the stuff to use `ultraviolet`, so things should at least turn on.

However, I did it pretty quickly, so the coordinate systems might not be correct. That would make stuff rotate the wrong directions and whatever. I don't have time to fiddle with it too much, but given this start you should be able to try the different Mat4 methods and such until things look right.

If you want to double check and PR any fixes that would be appreciated.

**Comment by Bricklou** [comment]
There's no problems. I have myself tried to run the program with `nalgebra-glm` and I didn't have any issue with it.
