### ISSUE TITLE
Update the examples to utilize the latest version of beryllium

### ISSUE THREAD

**Issue by mcsantiago** [rust-tutorials/learn-opengl#7]
I believe the latest is at beryllium 0.7.6. However, the library appears to have some breaking changes to the existing code, so some minor refactoring may be needed in the early examples.

**Comment by Lokathor** [comment]
oh, yeah, beryllium is a mess and probably no one should use it. But the windowing lib isn't really the point so i try not to worry too much.

if you want to update it that's cool though.

**Comment by staurosKaragiannis** [comment]
> oh, yeah, beryllium is a mess and probably no one should use it. But the windowing lib isn't really the point so i try not to worry too much.
> 
> if you want to update it that's cool though.

What should we use instead?

**Comment by Lokathor** [comment]
uh, winit, i guess?

I don't super like winit because their event loop stuff is kinda weird, but i mean it does run.

**Comment by mwithington** [comment]
Hey quick note, beryllium `"0.2.0-alpha.4"`is currently broken on mac 
<img width="229" alt="Screen Shot 2022-10-25 at 3 23 43 PM" src="https://user-images.githubusercontent.com/12395862/197863559-a3a5810f-e152-4c45-9db4-7c723851c024.png">
However it works with `0.3.0` have been having issues with building but that works. This is also not an m1 mac.

**Comment by Lokathor** [comment]
I don't really have time to keep beryllium up to date with mac changes. Maybe someone should replace it with a winit version?

**Comment by mwithington** [comment]
@Lokathor could I try and create a PR for this? I am super new to all this and I might be able to make a meaningful change.

**Comment by Lokathor** [comment]
yeah have at it

**Comment by Lokathor** [comment]
should be set now
